### ISSUE TITLE
grub2 password rule for STIG and CIS

### ISSUE THREAD

**Issue by dodys** [canonical/ubuntu-security-guide#12]
In 20.04 STIG benchmark rule https://www.stigviewer.com/stig/canonical_ubuntu_20.04_lts/2022-06-06/finding/V-238204
it is expected that grub2 password configuration for both UEFI-based and Non-UEFI-based systems, the configuration is done in `/boot/grub/grub.cfg` and not anymore on `/boot/efi/EFI/ubuntu/grub.cfg` for UEFI-based systems.
This is because on 22.04 grub `/boot/efi/EFI/ubuntu/grub.cfg` basically loads `/boot/grub/grub.cfg`.

This is different from 18.04 STIG that had two rules, one for [UEFI-based](https://www.stigviewer.com/stig/canonical_ubuntu_18.04_lts/2022-06-06/finding/V-219148) systems and one for [Non-UEFI-based](https://www.stigviewer.com/stig/canonical_ubuntu_18.04_lts/2022-06-06/finding/V-219147) systems.

This also affects CIS.

This a bug not exactly in usg but in ComplianceAsCode and it will be fixed there and a new usg version will be need with the new XCCDF file from ComplianceAsCode.

**Comment by litios** [comment]
@dodys 22.04 STIG should be 20.04 STIG, right? I was reviewing both the rule and the proposed fix and everything is about focal.

**Comment by dodys** [comment]
> @dodys 22.04 STIG should be 20.04 STIG, right? I was reviewing the rule and it's for focal so just to confirm this is for focal profile

oops, I fixed it now
