### ISSUE TITLE
usg not available for Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by alkisg** [canonical/ubuntu-security-guide#15]
Hi, while trying to enable usg on Ubuntu 22.04 I'm getting the following error:

```console
root@server:~# ua status
SERVICE          ENTITLED  STATUS    DESCRIPTION
cc-eal           yes       n/a       Common Criteria EAL2 Provisioning Packages
esm-infra        yes       enabled   UA Infra: Extended Security Maintenance (ESM)
fips             yes       n/a       NIST-certified core packages
fips-updates     yes       n/a       NIST-certified core packages with priority security updates
livepatch        yes       enabled   Canonical Livepatch service
usg              yes       n/a       Security compliance and audit tools

Enable services with: ua enable <service>

     Account: alkisg@...
Subscription: alkisg@...

root@server:~# ua enable usg
One moment, checking your subscription first
Ubuntu Security Guide is not available for Ubuntu 22.04 LTS (Jammy Jellyfish).
```

Is this a temporary issue, are we waiting for it to be developed later on, and if so, any ETA?
Thank you.

**Comment by dodys** [comment]
It does not exist because we still don't have the security benchmarks implemented. 
CIS was just published end of last month. STIG perhaps just next year.
No ETA so far as this is still to be planned.

**Comment by nnellanspdl** [comment]
Any update to this?  I'm working on a project to deploy multiple servers, and I'm now questioning if I should roll back to 20.04 LTS.

**Comment by dodys** [comment]
The target is the end of this cycle, which means by Ubuntu 23.04 release.

**Comment by okohll** [comment]
Does that mean 2024 for the next LTS release? Just a vote not to forget about this, USG is really useful to us.

**Comment by candrews** [comment]
> I would expect USG to be released by 2025

I'm unclear, are we saying that we have to wait until 2025 (2 more years) for there to a STIG available for Ubuntu 22.04?

**Comment by guimspace** [comment]
No. What they meant is that the USG benchmarks for 22.04 will be released around the time 23.04 is released. And CIS for 24.04 will take time because updates to CIS Benchmarks takes time - and 24.04 wasn't even released yet to begin with.

**Comment by dodys** [comment]
> No. What they meant is that the USG benchmarks for 22.04 will be released around the time 23.04 is released. And CIS for 24.04 will take time because updates to CIS Benchmarks takes time - and 24.04 wasn't even released yet to begin with.

exactly!

**Comment by dodys** [comment]
usg for 22.04 is available since last Friday, therefore I'm closing this issue. Thanks!

**Comment by nnellanspdl** [comment]
Thank you!  Could I ask for an updated tutorial for how to properly capture a golden image of 22.04 that is secured with USG?

**Comment by dodys** [comment]
> Thank you! Could I ask for an updated tutorial for how to properly capture a golden image of 22.04 that is secured with USG?

There's a tutorial in the making, still not sure when that will be published, but I would say most of the previous documentation/tutorial for 20.04 is still in line with 22.04. Whenever we get the new tutorial I will comment here with the URL.

**Comment by mgomezzul** [comment]
Hi @dodys ! Thanks for the update! What is necessary to use USG on Ubuntu 22.04 LTS? Still some stuff pending, besides the doc? Thanks again

**Comment by dodys** [comment]
> Hi @dodys ! Thanks for the update! What is necessary to use USG on Ubuntu 22.04 LTS? Still some stuff pending, besides the doc? Thanks again

Just a Ubuntu Pro subscription, other than that you are good to go, the tutorial for 20.04 still covers the basic usage of the tool.
I will try to get an ETA for the new tutorial and let you know here.

**Comment by hasnimehdi91** [comment]
You need to attach a subscription before using `usg`, here are the instructions to follow

```bash
sudo pro attach <token>
sudo pro enable usg 
sudo apt update 
sudo apt install -y usg
```

**Comment by ghexp** [comment]
> It does not exist because we still don't have the security benchmarks implemented. CIS was just published end of last month. STIG perhaps just next year. No ETA so far as this is still to be planned.

Released on 4 April by DISA.  What is the ETA for inclusion in usg?
https://public.cyber.mil/announcement/disa-releases-the-canonical-ubuntu-22-04-lts-security-technical-implementation-guide/
