### ISSUE TITLE
usg audit fails on sshd_configure_* even after successfully fixing the problem with a tailoring file

### ISSUE THREAD

**Issue by sellonen** [canonical/ubuntu-security-guide#17]
Hi,

My problem is very similar to a closed issue here, but I am not able to overcome the problem with suggested solutions: https://github.com/canonical/ubuntu-security-guide/issues/9

The `usg audit cis_level1_server` keeps complaining about the rules `AllowUsers, AllowGroups, DenyUsers, DenyGroups` even after I tried fixing it both manually and using the tailor file. In both cases the actual problem is solved (of course) and e.g. user is not able to login with ssh if not explicitly mentioned in AllowUsers. However, the audit will always fail.

First verify tailor file is ok:

```
# grep sshd.*valid ~/tailor.xml 
<xccdf:set-value idref="var_sshd_allow_users_valid">ubuntu</xccdf:set-value>
<xccdf:set-value idref="var_sshd_allow_groups_valid">ubuntu</xccdf:set-value>
<xccdf:set-value idref="var_sshd_deny_users_valid">root</xccdf:set-value>
<xccdf:set-value idref="var_sshd_deny_groups_valid">root</xccdf:set-value>
# grep sshd_configure ~/tailor.xml 
<xccdf:select idref="sshd_configure_allow_users" selected="true"/>
<xccdf:select idref="sshd_configure_deny_users" selected="true"/>
<xccdf:select idref="sshd_configure_allow_groups" selected="true"/>
<xccdf:select idref="sshd_configure_deny_groups" selected="true"/>
```

Then I do the tailoring with command: `# usg fix --tailoring-file ~/tailor.xml`

During the fixing, I assume it first runs audit, and complains the values have not been configured (which is true). However, it also claims to have fixed them and asks me to reboot.

```
Title   Restrict sshd user access via AllowGroups
Rule    sshd_configure_allow_groups
W: oscap:     Entity name 'value' from state (id: 'oval:ssg-ste_var_dif_num_valid_list_and_parameter_list_allow_groups:ste:1') not found in item (id: '11190522').
Result  fail

Title   Restrict sshd user access via AllowUsers
Rule    sshd_configure_allow_users
W: oscap:     Entity name 'value' from state (id: 'oval:ssg-ste_var_dif_num_valid_list_and_parameter_list_allow_users:ste:1') not found in item (id: '11190524').
Result  fail

Title   Restrict sshd user access via DenyGroups
Rule    sshd_configure_deny_groups
W: oscap:     Entity name 'value' from state (id: 'oval:ssg-ste_var_dif_num_valid_list_and_parameter_list_deny_groups:ste:1') not found in item (id: '11190526').
Result  fail

Title   Restrict sshd user access via DenyUsers
Rule    sshd_configure_deny_users
W: oscap:     Entity name 'value' from state (id: 'oval:ssg-ste_var_dif_num_valid_list_and_parameter_list_deny_users:ste:1') not found in item (id: '11190528').
Result  fail

Title   Remove the X Windows Package Group
Rule    package_xorg-x11-server-common_removed
Result  pass


 --- Starting Remediation ---
Title   Ensure authentication required for single user mode
Rule    single_user_authentication
Result  error

Title   Verify All Account Password Hashes are Shadowed with SHA512
Rule    accounts_password_all_shadowed_sha512
Result  error

Title   Ensure users own their home directories
Rule    accounts_users_own_home_directories
Result  error

Title   All Interactive User Home Directories Must Have mode 0750 Or Less Permissive
Rule    file_permissions_home_directories
Result  error

Title   Disable Kernel Parameter for IP Forwarding on IPv4 Interfaces
Rule    sysctl_net_ipv4_ip_forward
Result  fixed

Title   Ensure No World-Writable Files Exist
Rule    file_permissions_unauthorized_world_writable
Result  error

Title   Restrict sshd user access via AllowGroups
Rule    sshd_configure_allow_groups
Result  fixed

Title   Restrict sshd user access via AllowUsers
Rule    sshd_configure_allow_users
Result  fixed

Title   Restrict sshd user access via DenyGroups
Rule    sshd_configure_deny_groups
Result  fixed

Title   Restrict sshd user access via DenyUsers
Rule    sshd_configure_deny_users
Result  fixed

```

And indeed, the correct values are set by the tailoring:

```
# tail -n4 /etc/ssh/sshd_config
AllowGroups ubuntu
AllowUsers ubuntu
DenyGroups root
DenyUsers root
``` 

So I go and reboot the machine, and run audit with command: `# usg audit cis_level1_server`

```
Title   Restrict sshd user access via AllowGroups
Rule    sshd_configure_allow_groups
Result  fail

Title   Restrict sshd user access via AllowUsers
Rule    sshd_configure_allow_users
Result  fail

Title   Restrict sshd user access via DenyGroups
Rule    sshd_configure_deny_groups
Result  fail

Title   Restrict sshd user access via DenyUsers
Rule    sshd_configure_deny_users
Result  fail
```

However, notice that earlier it complained explicitly that it's "not found". After the tailor fix, there's just "fail".

I am running Ubuntu 20.04, some system information:

```
# pro --version
27.11.2~20.04.1
# pro status
SERVICE          ENTITLED  STATUS    DESCRIPTION
esm-infra        yes       enabled   Expanded Security Maintenance for Infrastructure
fips-updates     yes       enabled   NIST-certified core packages with priority security updates
livepatch        yes       disabled  Canonical Livepatch service
usg              yes       enabled   Security compliance and audit tools
# uname -a
Linux megflow-server 5.4.0-1007-fips #8-Ubuntu SMP Wed Jul 29 21:42:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dodys** [comment]
after reboot, did you run audit by passing the tailoring file? 
e.g.: `# usg audit --tailoring-file ~/tailor.xml`

**Comment by sellonen** [comment]
Thank you for a quick reply! I had not done it, and indeed it seems to give me a passing result:

```
Title   Restrict sshd user access via AllowGroups
Rule    sshd_configure_allow_groups
Result  pass

Title   Restrict sshd user access via AllowUsers
Rule    sshd_configure_allow_users
Result  pass

Title   Restrict sshd user access via DenyGroups
Rule    sshd_configure_deny_groups
Result  pass

Title   Restrict sshd user access via DenyUsers
Rule    sshd_configure_deny_users
Result  pass

``` 

However, shouldn't I be able to fix this manually too? I'd like our ansible scripts to write correct config in the `/etc/ssh/...`  files, and verify the installation running just `usg audit cis_level1_server`

**Comment by dodys** [comment]
If I understand you are doing part of the remediation in ansible and part using usg?
If yes, then I think you would need 2 different tailoring files.
one tailoring file for fixing, with those sshd rules not selected (and any other you might be fixing with ansible)
and one tailoring file for auditing, with those sshd rules selected and the variable value set to what your configuration has.

you can't just run `usg audit cis_level1_server1` because it will use the default value for the variables and that won't match yours.

**Comment by sellonen** [comment]
In fact I wasn't necessarily planning on doing any remediation with `usg`. The hope was that we just use `usg` to prove that our setup is compliant with CIS level one, but all the actual changes are done in with ansible. Is that a bad idea to use `usg` as purely an audit tool?

**Comment by dodys** [comment]
> In fact I wasn't necessarily planning on doing any remediation with `usg`. The hope was that we just use `usg` to prove that our setup is compliant with CIS level one, but all the actual changes are done in with ansible. Is that a bad idea to use `usg` as purely an audit tool?

I don't think it is a bad idea, just be sure to run `usg audit` with a tailoring file and keep the tailoring file up-to-date to your configuration and it should work.

**Comment by sellonen** [comment]
Unfortunately that still does not make sense to me. If I have defined `AllowedUsers` in my sshd configuration, why would `usg audit cis_level1_server`  fail the condition `sshd_configure_allow_users`. That is why I'm reporting this issue, it looks like a bug to me. Are you saying it's intended behaviour?

**Comment by dodys** [comment]
I'm gonna close this as it is not a real issue.
Let me know in case of issues/doubts.
