### ISSUE TITLE
Issue with `sudo usg fix cis_level1_server` after first run post reboot

### ISSUE THREAD

**Issue by yogeshbb** [canonical/ubuntu-security-guide#20]
1. On Ubuntu 22.04 [Azure D-Series v4 (D4ds_v4) VM], after first run `sudo usg fix cis_level1_server` which took more than 12Hrs, then asked for reboot and running usg fix again.
In second run it was stuck with below screen, then stopped it manually.
![Screenshot 2023-05-21 at 6 08 20 PM](https://github.com/canonical/ubuntu-security-guide/assets/114896543/8f748db5-956b-4b8f-983d-85a0c06b2075)

2. Also this step
Title   User Initialization Files Must Not Run World-Writable Programs
Rule    xccdf_org.ssgproject.content_rule_accounts_user_dot_no_world_writable_programs

took lot of time, any specific reasons? The htop while running this was showing
Command `/usr/lib/x86_64-linux-gnu/openscap/probe_textfilecontent54` with 100% CPU utilisation

**Comment by dodys** [comment]
> Yes #1 looks similar to the https://bugs.launchpad.net/usg/+bug/2019556 But for #2 any specific reasons or is it normal time that it takes?

how much time it took?

**Comment by setharnold** [comment]
And how much data was it scanning?

**Comment by yogeshbb** [comment]
Hi the usg fix was running for more than 12 hours on fresh launch with just mariadb installed on the server nothing else.

**Comment by dodys** [comment]
> Hi the usg fix was running for more than 12 hours on fresh launched VM with just mariadb (having with single db and a test table) installed on the server nothing else.

I don't think that relates to USG.
Are you able to reproduce it?

**Comment by yogeshbb** [comment]
Hi I am running again without any changes to the mirror, to reproduce on new server.
Any quick references to make changes in the mirror?

**Comment by dodys** [comment]
> Hi I am running again without any changes to the mirror, to reproduce on new server. Any quick references to make changes in the mirror?

edit your `/etc/apt/sources.list` and change all the urls to `http://archive.ubuntu.com/ubuntu` for example

**Comment by dodys** [comment]
Any new feedback on reproducing the issue?

**Comment by yogeshbb** [comment]
Hi sorry got off it, due to deadlines, I will revert in just couple of days if not we can close this. 
For now moving ahead without that fix, with 96.98% CIS level-1 score (which excluding rules:
xccdf_org.ssgproject.content_rule_accounts_user_dot_no_world_writable_programs, xccdf_org.ssgproject.content_rule_wireless_disable_interfaces)

**Comment by dodys** [comment]
closing this issue because of the lack of information.
