### ISSUE TITLE
Two xccdf rules appear to be incompatible

### ISSUE THREAD

**Issue by adam-vest** [canonical/ubuntu-security-guide#32]
Hello folks! I've found a fascinating situation that appears to put a sysadmin between a rock and a hard place when running `usg audit` against either the `cis_level1_server` or `cis_level2_server` profiles, and looking for all green. The situation is when the system is using sssd for network user authentication (either LDAP or Active Directory), and has enumeration either on or off in `sssd.conf` for the domain. With `enumerate = false`, the following rule results can be expected:

* xccdf_org.ssgproject.content_rule_accounts_user_interactive_home_directory_exists - PASS
* xccdf_org.ssgproject.content_rule_no_files_unowned_by_user FAIL

Conversely, if we set `enumerate = true`, the opposite results can be expected:

* xccdf_org.ssgproject.content_rule_accounts_user_interactive_home_directory_exists - FAIL
* xccdf_org.ssgproject.content_rule_no_files_unowned_by_user PASS

This situation will occur when there are users in the sssd domain that haven't logged in to the local system (ergo, not necessarily having a home directory created for them yet), and there doesn't really appear to be a happy solution that give passing results for both of these rules in this situation. Keeping enumerate on and just maintaining home directories for potentially hundreds (or more) of network users who may never actually log in to this system may not be practical; however, turning off enumerate would result in the "unowned_by_user" rule to fail, with the only recourse being to disable it (and no longer be able to reliably audit this particular facet).

Is there a way to modify these rules so that they can be compatible with each other, and have a situation where they can both pass when scanned against a system with network authentication?

Thanks!

**Comment by mpurg** [comment]
Fix will be added to next release of usg (22.04.6).

**Comment by adam-vest** [comment]
Great! Thanks for the fixup on that @mpurg !
