### ISSUE TITLE
xccdf_org.ssgproject.content_rule_package_timesyncd_installed failed when chrony is installed

### ISSUE THREAD

**Issue by adam-vest** [canonical/ubuntu-security-guide#36]
Howdy!

Something I've noticed on systems with chrony installed is that the usg audit (level1 or level2 server) will flag the `xccdf_org.ssgproject.content_rule_package_timesyncd_installed` rule as failed. In the strictest sense this is true, because at least on Jammy, the **systemd-timesyncd** and **chrony** debs conflict with each other, and cannot both be installed:

```
sudo apt install chrony
[sudo] password for adam:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  systemd-timesyncd
The following NEW packages will be installed:
  chrony
0 upgraded, 1 newly installed, 1 to remove and 11 not upgraded.
Need to get 290 kB of archives.
After this operation, 360 kB of additional disk space will be used.
Do you want to continue? [Y/n]
```
Obviously explicitly installing **chrony** is a user choice, so one could argue that a tailoring file that disabled that rule would be the right approach here; however, I could also see the argument being made that the subsequent removal of **systemd-timesyncd** is NOT a choice, and that since **chrony** can also serve as an ntp client (and thus satisfying the requirement of the rule), that the audit scan should instead mark the rule as "notapplicable" when it detects **chrony** being installed.

Thoughts?

**Comment by dodys** [comment]
In CIS benchmark you can only have one synchronization method.
USG defaults to `sytemd-timesyncd`. If you want to use `chrony` than you need to use the tailoring files and unselect `package_timesyncd_installed` and select `package_chrony_installed`.  That way `package_timesyncd_installed` won't be remediated nor audited and you won't see the fail in the report.

**Comment by adam-vest** [comment]
While I'm fine with the tailoring file suggestion, I think the argument could be made for consistency, however. Taking UFW as an example, those rules will always fail at least one of them:
* Remove ufw Package
* Verify ufw Enabled

Regardless of whether UFW is installed, one of those rules will be marked as failed, requiring a tailoring file for the admin to factor in their specific needs. In the same spirit, rather than tagging the "The Chronyd service is enabled" rule as "notapplicable" because it's not installed, shouldn't it instead report as failed?

**Comment by dodys** [comment]
> While I'm fine with the tailoring file suggestion, I think the argument could be made for consistency, however. Taking UFW as an example, those rules will always fail at least one of them:
> 
>     * Remove ufw Package
> 
>     * Verify ufw Enabled
> 
> 
> Regardless of whether UFW is installed, one of those rules will be marked as failed, requiring a tailoring file for the admin to factor in their specific needs. In the same spirit, rather than tagging the "The Chronyd service is enabled" rule as "notapplicable" because it's not installed, shouldn't it instead report as failed?

Hi Adam,

sorry I didn't understand what UFW has to do with this case here, could you please clarify?

**Comment by adam-vest** [comment]
Hi! I'm just using UFW as a point of demonstration. Currently, if one does not have UFW installed, then the `Verify ufw Enabled` rule will fail; conversely, if one DOES have UFW installed, then `Remove ufw Package` will fail. Either way, one rule will always fail, and it would then be up to the end-user to write a tailoring file to account for their specific needs.

Likewise for this systemd-timesynd/chrony thing, if we're going to be fair and consistent, then I think one of those rules should always fail, and the user should just use a tailoring file accordingly. However, right now if chrony isn't installed, the report simply marks it as "notapplicable". If it were consistent with the UFW rules, then that would instead be marked as a "fail".
