### ISSUE TITLE
The command 'usg --fix' is failing due to an issue with /etc/aide/aide.conf

### ISSUE THREAD

**Issue by David-Deming** [canonical/ubuntu-security-guide#40]
The problem: 
When running the command 'usg --fix cis_level2_server' I kept getting an error that using 'database=file:' in /etc/aide/aide.conf is deprecated and to use 'database_in=file:' instead.

Steps I took to fix it:
I edited /etc/aide/aide.conf and changed 'database=file:' to 'database_in=file:' and then re-ran 'usg --fix cis_level2_server'. It failed and I got the same error. I again checked /etc/aide/aide.conf and found that 'database=file:' had been added below the 'database_in=file:' line that I had edited. This led me to realize the script that is ran when running 'usg --fix cis_level2_server' was adding that to that config file every time it is ran.

I then went into the script it was running: /var/lib/usg/cis_level2_server-20240426.1817.sh and altered the if statement that was echoing 'database=file:' into /etc/aide/aide.conf to instead echo 'database_in:file'. I ran it again and got the same error because it ran a different version of the script from the one I had edited. 1850.sh instead of 1817.sh. 

In order to ensure it ran the version of the script I had edited I manually ran the full command that 'usg --fix' was running: 'bash -x /var/lib/usg/cis_level2_server-20240426.1817.sh 2>&1 1>remediation-20240426.1817.log | tee -a remediation-20240426.1817'

I got the same error. So this time I edited the same script and commented out the whole if statement that was echoing 'database=file:' into /etc/aide/aide.conf and ran the command manually again. Then it ran the script successfully and remediated my server to cis level2 benchmark. I think it would have failed if I had not added 'database_in=file:' to /etc/aide/aide.conf since the section that would have added it in was commented out.

It sounds like that script that the command 'usg --fix' calls needs to be altered to incorporate 'database_in=file:' instead of 'database=file:'

**Comment by dodys** [comment]
Issues to usg should be reported in launchpad: https://bugs.launchpad.net/usg
Pleas einclude the version of usg, the version of ubuntu and run the failing command with --debug and upload the logs.
