### ISSUE TITLE
Benchmark issue with cis_level2_server 

### ISSUE THREAD

**Issue by SBDJUK** [canonical/ubuntu-security-guide#9]
Hi,

I don't know if this is the right place to report this. I've been to #ubuntu-bugs who directed me to #ubuntu-security who directed me here. Given that the problem could be in the benchmark file itself I'm not sure.

I have usg 20.04.15 installed on Ubuntu Pro and I'm getting a fail:

```
Title Restrict sshd user access via AllowGroups
Rule sshd_configure_allow_groups
Result fail

root@host:~# sshd -T | grep allowgroups
allowgroups aad_admins
```

As you can see the restriction is set. I note someone else has tried to report the same/very similar issue on launchpad (https://bugs.launchpad.net/ubuntu/+bug/1979155)

The profile in use is CIS Ubuntu 20.04 Level 2 Server Benchmark (/usr/share/ubuntu-scap-security-guides/current/benchmarks/Canonical_Ubuntu_20.04_Benchmarks-xccdf.xml).

**Comment by dodys** [comment]
Hey SBDJ,

I've checked here, and I think you only need to follow the https://ubuntu.com/security/certifications/docs/usg/cis/customization

Basically run:
`$ sudo usg generate-tailoring cis_level2_server tailor.xml`

edit your tailor.xml on var_sshd_allow_groups_valid to be something like: 
`<xccdf:set-value idref="var_sshd_allow_groups_valid">aad_admins</xccdf:set-value>`

then run:
`$ sudo usg audit --tailoring-file tailor.xml`

**Comment by SBDJUK** [comment]
Thanks - I can confirm that creating a tailoring file and specifying the groups there works. I probably should have worked that out; as I said in #ubuntu-security it was probably user error!

**Comment by dodys** [comment]
thanks for testing and confirming it!
